#!/usr/bin/env bash
# ==============================================================================
# report.sh — Stage 4: Report generation
# ==============================================================================

report_menu() {
    ask_menu "Report output — what should we generate?" 2 \
        "Plain text only  (scan.txt, findings.txt, summary.txt)" \
        "Plain text + HTML report (recommended)" \
        "Plain text + HTML + keep raw nmap grepable output"
    REPORT_MODE="$MENU_CHOICE"
}

_severity_rank() {
    case "$1" in
        HIGH) echo 3 ;; MEDIUM) echo 2 ;; LOW) echo 1 ;; *) echo 0 ;;
    esac
}

generate_findings_file() {
    {
        printf 'FINDINGS — %s\n' "$TARGET"
        printf 'Generated: %s\n' "$(date '+%Y-%m-%d %H:%M:%S')"
        printf '%s\n\n' "======================================================================"

        if (( ${#FINDINGS[@]} == 0 )); then
            printf 'No findings were recorded for this target.\n'
        else
            local f severity title evidence recommendation n=1
            for f in "${FINDINGS[@]}"; do
                IFS='|' read -r severity title evidence recommendation <<< "$f"
                printf '[%d] SEVERITY: %s\n' "$n" "$severity"
                printf '    Title:          %s\n' "$title"
                printf '    Evidence:       %s\n' "$evidence"
                printf '    Recommendation: %s\n\n' "$recommendation"
                ((n++))
            done
        fi
    } > "$FINDINGS_FILE"
}

generate_summary_file() {
    local high=0 medium=0 low=0 info=0
    local f severity
    for f in "${FINDINGS[@]}"; do
        severity="${f%%|*}"
        case "$severity" in
            HIGH) ((high++)) ;; MEDIUM) ((medium++)) ;; LOW) ((low++)) ;; INFO) ((info++)) ;;
        esac
    done

    local risk="Low"
    (( medium > 0 )) && risk="Medium"
    (( high > 0 )) && risk="High"

    {
        printf 'SECURITY ASSESSMENT SUMMARY\n'
        printf '======================================================================\n'
        printf 'Target:        %s\n' "$TARGET"
        printf 'Resolved IP:   %s\n' "${TARGET_IP:-n/a}"
        printf 'Scan date:     %s\n' "$(date '+%Y-%m-%d %H:%M:%S')"
        printf 'Duration:      %s\n' "$(human_duration "$SCAN_DURATION")"
        printf '\nScan profile:\n'
        printf '  Firewall evasion:     %s\n' "$([[ "$FW_EVADE" == "1" ]] && echo "Yes (Xmas scan)" || echo "No")"
        printf '  Protocol:             %s\n' "${SCAN_PROTOCOL^^}"
        printf '  Operational profile:  %s\n' "$([[ "$STEALTH_PROFILE" == "redteam" ]] && echo "Red Team (maximum stealth)" || echo "Penetration Test (standard)")"
        printf '  Technique used:       %s\n' "$SCAN_TECHNIQUE_LABEL"
        printf '  Stealth measures:     %s\n' "$STEALTH_LABEL"
        printf '\nOpen ports (%d):\n' "${#OPEN_PORTS[@]}"
        if (( ${#OPEN_PORTS[@]} > 0 )); then
            for p in "${!OPEN_PORTS[@]}"; do
                printf '  - %-6s %-10s %s\n' "$p" "${OPEN_PORTS[$p]}" "${PORT_VERSION[$p]:-}"
            done | sort -n
        else
            printf '  (none detected)\n'
        fi
        printf '\nFindings by severity:\n'
        printf '  HIGH:   %d\n  MEDIUM: %d\n  LOW:    %d\n  INFO:   %d\n' "$high" "$medium" "$low" "$info"
        printf '\nOverall risk rating: %s\n' "$risk"
        printf '\nRisk explanation:\n'
        case "$risk" in
            High)   printf '  At least one HIGH severity, evidence-backed finding was confirmed.\n  These typically allow unauthorized access or information disclosure\n  and should be remediated before this host is exposed further.\n' ;;
            Medium) printf '  No HIGH severity findings, but MEDIUM findings indicate weaknesses\n  (e.g. outdated software, information disclosure) that reduce the\n  effort needed for further compromise and should be scheduled for fixes.\n' ;;
            *)      printf '  No HIGH/MEDIUM findings confirmed during this assessment. This does\n  not guarantee the host is fully secure — it reflects only the checks\n  this tool performed.\n' ;;
        esac
        printf '\nRecommendations:\n'
        if (( ${#FINDINGS[@]} == 0 )); then
            printf '  - Maintain current patching and configuration hygiene.\n  - Consider deeper manual testing beyond this tool'"'"'s automated checks.\n'
        else
            local f severity title _e recommendation
            for f in "${FINDINGS[@]}"; do
                IFS='|' read -r severity title _e recommendation <<< "$f"
                printf '  - [%s] %s: %s\n' "$severity" "$title" "$recommendation"
            done
        fi
        printf '\n----------------------------------------------------------------------\n'
        printf 'Generated by KarScan (karscan.sh) — Instant Software Solutions security track\n'
    } > "$SUMMARY_FILE"
}

generate_html_report() {
    local high=0 medium=0 low=0 info=0
    local f severity
    for f in "${FINDINGS[@]}"; do
        severity="${f%%|*}"
        case "$severity" in
            HIGH) ((high++)) ;; MEDIUM) ((medium++)) ;; LOW) ((low++)) ;; INFO) ((info++)) ;;
        esac
    done
    local risk="Low" risk_color="#2e7d32"
    (( medium > 0 )) && { risk="Medium"; risk_color="#e6a700"; }
    (( high > 0 )) && { risk="High"; risk_color="#c0392b"; }

    {
cat <<HTML_HEAD
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Security Assessment Report — ${TARGET}</title>
<style>
  :root { color-scheme: light; }
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; background:#f5f6f8; color:#1b1f24; margin:0; padding:40px 20px; }
  .wrap { max-width: 900px; margin: 0 auto; }
  header { border-bottom: 3px solid #c0392b; padding-bottom: 16px; margin-bottom: 24px; }
  h1 { margin: 0 0 4px 0; font-size: 26px; }
  .meta { color:#5a636e; font-size: 14px; }
  .badge { display:inline-block; padding:4px 12px; border-radius:20px; color:#fff; font-weight:600; font-size:13px; }
  .card { background:#fff; border:1px solid #e2e5e9; border-radius:10px; padding:20px 24px; margin-bottom:20px; box-shadow:0 1px 2px rgba(0,0,0,.04); }
  table { width:100%; border-collapse: collapse; font-size: 14px; }
  th, td { text-align:left; padding:8px 10px; border-bottom:1px solid #eee; vertical-align: top; }
  th { color:#5a636e; font-weight:600; }
  .sev { display:inline-block; padding:2px 10px; border-radius: 12px; color:#fff; font-size:12px; font-weight:700; }
  .sev-HIGH { background:#c0392b; } .sev-MEDIUM { background:#e6a700; } .sev-LOW { background:#3468c0; } .sev-INFO { background:#7a8390; }
  .evidence { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12.5px; background:#f2f3f5; padding:8px 10px; border-radius:6px; display:block; margin-top:4px; white-space:pre-wrap; word-break: break-word; }
  footer { text-align:center; color:#9aa1a9; font-size:12px; margin-top:30px; }
  .stat-row { display:flex; gap:16px; flex-wrap:wrap; }
  .stat { flex:1; min-width:110px; background:#fff; border:1px solid #e2e5e9; border-radius:10px; padding:14px 18px; text-align:center; }
  .stat .num { font-size:26px; font-weight:700; }
</style>
</head>
<body>
<div class="wrap">
<header>
  <h1>Security Assessment Report</h1>
  <div class="meta">Target: <strong>${TARGET}</strong> (${TARGET_IP:-n/a}) &middot; Generated ${SCAN_DATE_HUMAN}</div>
  <span class="badge" style="background:${risk_color}">Overall risk: ${risk}</span>
</header>

<div class="stat-row">
  <div class="stat"><div class="num">${#OPEN_PORTS[@]}</div>Open ports</div>
  <div class="stat"><div class="num" style="color:#c0392b">${high}</div>High</div>
  <div class="stat"><div class="num" style="color:#e6a700">${medium}</div>Medium</div>
  <div class="stat"><div class="num" style="color:#3468c0">${low}</div>Low</div>
  <div class="stat"><div class="num" style="color:#7a8390">${info}</div>Info</div>
</div>

<div class="card">
  <h2>Scan Profile</h2>
  <table>
    <tr><th>Firewall evasion</th><td>$([[ "$FW_EVADE" == "1" ]] && echo "Yes (Xmas scan)" || echo "No")</td></tr>
    <tr><th>Protocol</th><td>${SCAN_PROTOCOL^^}</td></tr>
    <tr><th>Operational profile</th><td>$([[ "$STEALTH_PROFILE" == "redteam" ]] && echo "Red Team (maximum stealth)" || echo "Penetration Test (standard)")</td></tr>
    <tr><th>Technique used</th><td>$(_html_escape "$SCAN_TECHNIQUE_LABEL")</td></tr>
    <tr><th>Stealth measures</th><td>$(_html_escape "$STEALTH_LABEL")</td></tr>
  </table>
</div>

<div class="card">
  <h2>Open Ports &amp; Services</h2>
  <table>
    <tr><th>Port</th><th>Service</th><th>Version / Banner</th></tr>
HTML_HEAD

        if (( ${#OPEN_PORTS[@]} > 0 )); then
            for p in "${!OPEN_PORTS[@]}"; do
                printf '<tr><td>%s</td><td>%s</td><td>%s</td></tr>\n' "$p" "${OPEN_PORTS[$p]}" "$(_html_escape "${PORT_VERSION[$p]:-}")"
            done | sort -n
        else
            printf '<tr><td colspan="3">No open ports detected</td></tr>\n'
        fi

cat <<'HTML_MID'
  </table>
</div>

<div class="card">
  <h2>Findings</h2>
HTML_MID

        if (( ${#FINDINGS[@]} == 0 )); then
            printf '<p>No findings were recorded for this target.</p>\n'
        else
            local n=1 title evidence recommendation
            for f in "${FINDINGS[@]}"; do
                IFS='|' read -r severity title evidence recommendation <<< "$f"
                cat <<FINDING_HTML
  <div style="padding:12px 0; border-top:1px solid #f0f0f0;">
    <span class="sev sev-${severity}">${severity}</span>
    <strong style="margin-left:8px;">$(_html_escape "$title")</strong>
    <span class="evidence">$(_html_escape "$evidence")</span>
    <div style="margin-top:6px; color:#4a525c; font-size:13.5px;"><strong>Recommendation:</strong> $(_html_escape "$recommendation")</div>
  </div>
FINDING_HTML
                ((n++))
            done
        fi

cat <<'HTML_TAIL'
</div>
<footer>Generated by KarScan (karscan.sh) — Instant Software Solutions security track</footer>
</div>
</body>
</html>
HTML_TAIL
    } > "$HTML_FILE"
}

_html_escape() {
    local s="$1"
    s="${s//&/&amp;}"; s="${s//</&lt;}"; s="${s//>/&gt;}"; s="${s//\"/&quot;}"
    printf '%s' "$s"
}

generate_reports() {
    section "Stage 4/4 — Report Generation"
    SCAN_DATE_HUMAN="$(date '+%Y-%m-%d %H:%M:%S')"

    generate_findings_file
    log_ok "Findings written to $FINDINGS_FILE"

    generate_summary_file
    log_ok "Summary written to $SUMMARY_FILE"

    log_ok "Raw scan log written to $SCAN_FILE"

    if [[ "$REPORT_MODE" != "1" ]]; then
        generate_html_report
        log_ok "HTML report written to $HTML_FILE"
    fi

    printf '\n'
    banner "Report ready: $REPORT_DIR"
}
